added info admonitions
AdguardTeam/KnowledgeBaseDNS pull request #110
Opened 2023-06-06 14:00 UTC by el-termikael

2023-06-07 15:19 UTC, Alex-302 requested changes

2023-06-07 15:19 UTC, Alex-302 commented on docs/general/dns-filtering-syntax.md
> +Quick links: [Download AdGuard Ad Blocker](https://adguard.com/download.html?auto=true), [Get AdGuard Home](https://github.com/AdguardTeam/AdGuardHome#getting‒started), [Try AdGuard DNS](https://adgu
Нерабочий якорь для AG Home 
```suggestion
Quick links: [Download AdGuard Ad Blocker](https://adguard.com/download.html?auto=true), [Get AdGuard Home](https://github.com/AdguardTeam/AdGuardHome#getting-started), [Try AdGuard DNS](https://adguard‒dns.io/dashboard/)
```

2023-06-07 15:19 UTC, Alex-302 commented on docs/general/dns-filtering.md
> +Quick links: [Download AdGuard Ad Blocker](https://adguard.com/download.html?auto=true), [Get AdGuard Home](https://github.com/AdguardTeam/AdGuardHome#getting‒started), [Try AdGuard DNS](https://adgu
```suggestion
Quick links: [Download AdGuard Ad Blocker](https://adguard.com/download.html?auto=true), [Get AdGuard Home](https://github.com/AdguardTeam/AdGuardHome#getting-started), [Try AdGuard DNS](https://adguard‒dns.io/dashboard/)
```

2023-06-07 15:19 UTC, Alex-302 commented on docs/public-dns/solving-problems/how-to-flush-dns-cache.md
> +To avoid the above problems, you need to clear the DNS cache: to delete all saved DNS lookup information so that the next time you send a lookup request, your computer receives updated data from DNS
Очистка кэша не поможет, если система [всё ещё] заражена тем, что изменяет кэш или файл HOSTS.

2023-06-07 15:19 UTC, Alex-302 commented on docs/public-dns/solving-problems/how-to-flush-dns-cache.md
> +### Chrome
Лучше `Chrome browser`, и передвинуть в конец, т.к. выше и ниже перечисляются операционные системы и системная служба.

2023-06-08 09:10 UTC, Chinaski1 approved these changes

2023-06-09 07:51 UTC, ameshkov approved these changes

2023-06-09 07:51 UTC, ameshkov commented on docs/public-dns/solving-problems/how-to-flush-dns-cache.md
> +To avoid the above problems, you need to clear the DNS cache: to delete all saved DNS lookup information so that the next time you send a lookup request, your computer receives updated data from DNS
Ну мы такое не пытаемся тут полечить

2023-06-12 11:14 UTC, Alex-302 approved these changes

2023-06-16 10:02 UTC, merged