Add Linked IP to the Overview
AdguardTeam/KnowledgeBaseDNS pull request #117
Opened 2023-06-29 13:13 UTC by aalpatkina

2023-06-29 13:42 UTC, el-termikael approved these changes

2023-06-29 15:33 UTC, ameshkov requested changes
Instead of adding a new section you should do the following:

Extend the "How to set up Private AdGuard DNS" section.

Explain that every "Device" that you add in AdGuard DNS panel has its own unique address that can be used if the device supports modern encrypted DNS protocols (DoH, DoT, DoQ).

If the device does not support encrypted DNS and you have to use plain DNS, there's another way to allow AdGuard DNS to recognize the device. This way is to link its IP address. In this case AdGuard DNS counts all plain DNS queries that come from that IP address towards that "Device".

The only requirement is that it must be a residential IP address (ask chatGPT what is it).

If you're trying to link a residential IP address and AdGuard DNS does not allow you to do that, please contact our support service.

2023-07-03 09:03 UTC, el-termikael approved these changes

2023-07-03 09:19 UTC, ameshkov requested changes
We need to have a section for Linked IP so that we could link that section directly from other places

2023-07-03 09:19 UTC, ameshkov commented on docs/private-dns/overview.md
> +If the device does not support encrypted DNS and you have to use plain DNS, there's another way to allow AdGuard DNS to recognize the device — link its IP address. In this case AdGuard DNS counts all
```suggestion
### Linked IP

If the device does not support encrypted DNS and you have to use plain DNS, there's another way to allow AdGuard DNS to recognize the device — link its IP address. In this case AdGuard DNS counts all plain DNS requests that come from that IP address towards that "device".
```

2023-07-03 12:48 UTC, ameshkov approved these changes

2023-07-03 14:35 UTC, merged