[GH-138] iCloud Private Relay issue explained
AdguardTeam/KnowledgeBaseDNS pull request #143
Opened 2023-09-14 14:20 UTC by vbagirov

Closes #138

2023-09-14 16:15 UTC, slavaleleka commented on docs/private-dns/solving-problems/icloud-private-relay.md
> +    ![iCloud Private Relay settings *mobile](https://cdn.adtidy.org/content/kb/dns/private/solving_problems/icloud_private_relay/icloudpr.jpg)
тут тоже надо таб иначе нумерация сбивается
https://uploads.adguard.org/slbdzdrv4msv7.png

2023-09-14 16:16 UTC, slavaleleka commented on docs/private-dns/solving-problems/icloud-private-relay.md
> +    ![iCloud Private Relay settings *mobile](https://cdn.adtidy.org/content/kb/dns/private/solving_problems/icloud_private_relay/icloudpr.jpg)
в вскоде есть предпросмотр макрдауна
https://uploads.adguard.org/slbdzdrv095wj.png

2023-09-14 16:25 UTC, slavaleleka approved these changes

2023-09-15 09:54 UTC, el-termikael requested changes

2023-09-15 09:54 UTC, el-termikael commented on docs/private-dns/solving-problems/icloud-private-relay.md
> +When you're using iCloud Private Relay, AdGuard DNS dashboard (and associated [AdGuard test page](https://adguard.com/en/test.html)) will show that you are not using AdGuard DNS on that device.
мы не оставляем локаль в ссылках на сайт

2023-09-15 09:54 UTC, el-termikael commented on docs/private-dns/solving-problems/icloud-private-relay.md
> +    1. In Safari, choose **View** → **Reload and Show IP Address**.
точка

2023-09-15 09:54 UTC, el-termikael commented on docs/private-dns/solving-problems/icloud-private-relay.md
> +If you can't see the option to temporarily allow a website to see your IP address, update your device to the latest version of iOS, iPadOS or macOS, then try again.
```suggestion
If you can't see the option to temporarily allow a website to see your IP address, update your device to the latest version of iOS, iPadOS, or macOS, then try again.
```

2023-09-15 10:32 UTC, el-termikael approved these changes

2023-09-15 10:32 UTC, merged