Fix typos
AdguardTeam/KnowledgeBaseDNS pull request #148
Opened 2023-10-12 07:36 UTC by gork7777

2023-11-07 10:55 UTC, el-termikael requested changes

2023-11-07 10:55 UTC, el-termikael commented on docs/general/dns-providers.md
> +#### OSZX Server
```suggestion
#### OSZX DNS
```

2023-11-07 10:55 UTC, el-termikael commented on docs/general/dns-providers.md
> +#### PumpleX Server
```suggestion
#### PumpleX server
```

2023-11-07 10:55 UTC, el-termikael commented on i18n/en/code.json
> +    "message": "Blog recent posts navigation",
```suggestion
    "message": "Recent blog posts navigation",
```

2024-01-11 13:51 UTC, anastasiia-fedotova approved these changes
but first resolve conflicts

2024-01-12 11:47 UTC, el-termikael approved these changes

2024-01-12 11:51 UTC, merged