Add an article about deleting a DNS profile
AdguardTeam/KnowledgeBaseDNS pull request #149
Opened 2023-10-12 16:29 UTC by ss-orlova

2023-10-13 09:24 UTC, Chinaski1 approved these changes

2023-10-13 12:08 UTC, el-termikael requested changes

2023-10-13 12:08 UTC, el-termikael commented on docs/private-dns/solving-problems/delete-dns-profile.md
> +title: How to delete a DNS profile
кстати, по редполитике не remove ли?

2023-10-13 12:08 UTC, el-termikael commented on docs/private-dns/solving-problems/delete-dns-profile.md
> +1. Confirm the deletion.
deletion –> action

2023-10-13 12:08 UTC, el-termikael commented on docs/private-dns/solving-problems/delete-dns-profile.md
> +1. Enter your device password to confirm the deletion.
я крч за removal

2023-10-13 16:36 UTC, ss-orlova commented on docs/private-dns/solving-problems/delete-dns-profile.md
> +title: How to delete a DNS profile
хм ну может и ремув

2023-10-16 13:21 UTC, el-termikael approved these changes

2023-10-16 13:24 UTC, merged