Revamp the known DNS providers article
AdguardTeam/KnowledgeBaseDNS pull request #153
Opened 2023-10-18 13:04 UTC by anastasiia-fedotova

- restructure the article
- remove dead dns providers
- add new ones

2023-10-19 12:34 UTC, el-termikael requested changes

2023-10-19 12:34 UTC, el-termikael commented on docs/general/dns-providers.md
> +Other DNS servers with 'no logging' policy.
```suggestion
Other DNS servers with no-logging policy.
```

2023-10-19 12:34 UTC, el-termikael commented on docs/general/dns-providers.md
> +[DNS.SB](https://dns.sb/) provide free DNS service with no logging, DNSSEC enabled.
```suggestion
[DNS.SB](https://dns.sb/) provides free DNS service without logging and with DNSSEC enabled.
```

2023-10-19 12:34 UTC, el-termikael commented on docs/general/dns-providers.md
> +A collaborative open project to promote, implement and deploy [DNS Privacy](https://dnsprivacy.org/).
```suggestion
A collaborative open project to promote, implement, and deploy [DNS Privacy](https://dnsprivacy.org/).
```

2023-10-19 12:34 UTC, el-termikael commented on docs/general/dns-providers.md
> +[DNSlify DNS](https://www.dnslify.com/services/) operate public DNS resolvers to speed up requests, increase redundancy. The service is provided by [Peerix](https://www.peerix.net/)
```suggestion
[DNSlify DNS](https://www.dnslify.com/services/) operates public DNS resolvers to speed up requests and increase redundancy. The service is provided by [Peerix](https://www.peerix.net/).
```

2023-10-19 12:34 UTC, el-termikael commented on docs/general/dns-providers.md
> +Safe mode guard against infected, fraudulent or bot sites.
```suggestion
Safe mode guards against infected, fraudulent, or bot sites.
```

2023-10-19 12:34 UTC, el-termikael commented on docs/general/dns-providers.md
> +Family mode offers protection by "Safe" resolvers and blocks adult sites.
звучит непонятно

2023-10-19 12:34 UTC, el-termikael commented on docs/general/dns-providers.md
> +[NextDNS](https://nextdns.io/) provides publicly accessible non-filtering resolvers with no logging in addition to its freemium configurable filtering resolvers with optional logging.
```suggestion
[NextDNS](https://nextdns.io/) provides publicly accessible non-filtering resolvers without logging in addition to its freemium configurable filtering resolvers with optional logging.
```

2023-10-19 12:34 UTC, el-termikael commented on docs/general/dns-providers.md
> +These servers provide no ad blocking, keep no logs, and have DNSSEC enabled.
в заголовке сервер, в описании уже серверы

2023-10-19 14:12 UTC, anastasiia-fedotova commented on docs/general/dns-providers.md
> +Family mode offers protection by "Safe" resolvers and blocks adult sites.
удалила этого провайдера, т.к. ни один сайт не работает

2023-10-19 15:29 UTC, el-termikael approved these changes

2023-10-22 20:31 UTC, ameshkov requested changes
I don't see any toc changes requested in the issue

2023-10-31 14:55 UTC, ameshkov approved these changes

2023-11-01 06:13 UTC, merged