[AGM-1831] Add DoT/Non-filtered OpenDNS servers
AdguardTeam/KnowledgeBaseDNS pull request #157
Opened 2023-11-15 12:43 UTC by puglieri

2023-11-15 15:34 UTC, zzebrum approved these changes

2023-11-15 16:36 UTC, el-termikael requested changes

2023-11-15 16:36 UTC, el-termikael commented on docs/general/dns-providers.md
> +| DNS, IPv4      | `208.67.222.2` and `208.67.220.2`                  | [Add to AdGuard](adguard:add_dns_server?address=208.67.220.2&name=), [Add to AdGuard VPN](adguardvpn:add_dns_server?address=208
тут не хватает после name=

2023-11-15 16:36 UTC, el-termikael commented on docs/general/dns-providers.md
> +| DNS, IPv6      | `2620:0:ccc::2` IP: `2620:0:ccd::2`| [Add to AdGuard](adguard:add_dns_server?address=2620:0:ccc::2&name=), [Add to AdGuard VPN](adguardvpn:add_dns_server?address=2620:0:ccc::2&name
и тут

2023-11-16 14:34 UTC, Chinaski1 commented on docs/general/dns-providers.md
> +| DNS, IPv4      | `208.67.222.2` and `208.67.220.2`                  | [Add to AdGuard](adguard:add_dns_server?address=208.67.220.2&name=), [Add to AdGuard VPN](adguardvpn:add_dns_server?address=208
Речь ведь об OpenDNS?

Все зависит от сервера, в данном случае я вижу просто Regular, поэтому можно написать `name=OpenDNS Regular`

2023-11-16 14:35 UTC, Chinaski1 commented on docs/general/dns-providers.md
> +| DNS, IPv4      | `208.67.222.2` and `208.67.220.2`                  | [Add to AdGuard](adguard:add_dns_server?address=208.67.220.2&name=), [Add to AdGuard VPN](adguardvpn:add_dns_server?address=208
Но если вы оставите поле пустым, тоже не будет критично, мы вроде бы только для наших серверов заморачивались с неймингом. Там пусть юзеры сами пишут. Короче это остается на ваше усмотрение.

2023-11-16 14:41 UTC, Chinaski1 commented on docs/general/dns-providers.md
> +| DNS, IPv4      | `208.67.222.2` and `208.67.220.2`                  | [Add to AdGuard](adguard:add_dns_server?address=208.67.220.2&name=), [Add to AdGuard VPN](adguardvpn:add_dns_server?address=208
Проясню где это имя потом показывает, вот к примеру возьмем [AdGuard DNS TLS](https://uploads.adguard.org/Chinaskikurd5.png) ->[ Вот его Имя](https://uploads.adguard.org/Chinaskiwusa6.png) уже в самом Адике при добавлении

2023-11-16 15:32 UTC, el-termikael commented on docs/general/dns-providers.md
> +| DNS, IPv4      | `208.67.222.2` and `208.67.220.2`                  | [Add to AdGuard](adguard:add_dns_server?address=208.67.220.2&name=), [Add to AdGuard VPN](adguardvpn:add_dns_server?address=208
ага, спасибо, Кость
тогда оставим как есть, пожалуй

2023-11-16 15:33 UTC, el-termikael approved these changes

2023-11-16 16:36 UTC, merged