fix dns filtering syntax anchors
AdguardTeam/KnowledgeBaseDNS pull request #169
Opened 2024-01-09 19:55 UTC by slavaleleka

2024-01-09 20:05 UTC, el-termikael requested changes

2024-01-09 20:05 UTC, el-termikael commented on docs/general/dns-filtering-syntax.md
> +## Basic Examples {#basic-examples}
```suggestion
## Basic examples {#basic-examples}

2024-01-09 20:05 UTC, el-termikael commented on docs/general/dns-filtering-syntax.md
> +## Basic Examples {#basic-examples}
вообще по-хорошему избавиться бы от title case
по редполитике у нас sentence case, разве что macOS это не касается: https://www.notion.so/adguard/0df1a9bec9464fbf88bd813312ab0c26

2024-01-09 20:05 UTC, el-termikael commented on docs/general/dns-filtering-syntax.md
> +## Adblock-Style Syntax {#adblock-style-syntax}
syntax
и ниже в подзаголовках

2024-01-09 20:05 UTC, el-termikael commented on docs/general/dns-filtering-syntax.md
> +If you are maintaining a blocklist and use different sources in it, [Hostlist compiler] may be useful to you. It is a simple tool that makes it easier to compile a hosts blocklist compatible with AdG
а в подзаголовке Hostlists — почему тут решил поменять?

2024-01-09 20:49 UTC, slavaleleka commented on docs/general/dns-filtering-syntax.md
> +If you are maintaining a blocklist and use different sources in it, [Hostlist compiler] may be useful to you. It is a simple tool that makes it easier to compile a hosts blocklist compatible with AdG
тут поменял потому что репа именно так называется
https://github.com/AdguardTeam/HostlistCompiler

2024-01-09 20:54 UTC, el-termikael commented on docs/general/dns-filtering-syntax.md
> +If you are maintaining a blocklist and use different sources in it, [Hostlist compiler] may be useful to you. It is a simple tool that makes it easier to compile a hosts blocklist compatible with AdG
давай тогда и в подзаголовке так назовём

2024-01-11 07:11 UTC, el-termikael approved these changes

2024-01-11 10:32 UTC, merged