Add AdGuard DNS Client information
AdguardTeam/KnowledgeBaseDNS pull request #212
Opened 2024-06-13 15:51 UTC by ainar-g

2024-06-13 16:02 UTC, ainar-g commented on docs/dns-client/configuration.md
> +        - `question_domain`: The domain or a suffix of the domain that the set of upstream servers should be used to resolve.
This section causes issues with `docusaurus` 2.4.3 on my machine.  I wasn't able to find a way to make both `docusaurus` and `markdownlint` happy about it.

2024-06-13 17:15 UTC, ameshkov approved these changes

2024-06-14 09:50 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +The `dns` object configures the behavior of DNS server. It has the following properties:
```suggestion
The `dns` object configures the behavior of the DNS server. It has the following properties:
```

2024-06-14 09:50 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +The `dns` object configures the behavior of DNS server. It has the following properties:
а тут будут проперти?

2024-06-14 09:51 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +- `size`: The maximum size of the DNS results cache as human-readable data size. It must be greater than zero if `enabled` is `true`.
```suggestion
- `size`: The maximum size of the DNS results cache in human-readable data size. It must be greater than zero if `enabled` is `true`.
```

2024-06-14 09:54 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +- `client_size`: The maximum size of the DNS results cache for each configured client’s address or subnetwork as human-readable data size. It must be greater than zero if `enabled` is `true`.
```suggestion
- `client_size`: The maximum size of the DNS result cache for each configured client address or subnetwork in human-readable data size. It must be greater than zero if `enabled` is `true`.
```

2024-06-14 09:55 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +The `bootstrap` object configures the resolving of [upstream](#dns-upstream) servers addresses. It has the following properties:
```suggestion
The `bootstrap` object configures the resolving of [upstream](#dns-upstream) server addresses. It has the following properties:
```

2024-06-14 09:55 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +The `bootstrap` object configures the resolving of [upstream](#dns-upstream) servers addresses. It has the following properties:
+ resolving → resolution?

2024-06-14 09:59 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +- `servers`: The list of servers to use for resolving upstream servers hostnames.
```suggestion
- `servers`: The list of servers to resolve the hostnames of upstream servers.
```

2024-06-14 10:15 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +        - `client`: The client’s address or a subnet of the client’s address that the set of upstream servers should be used to resolve requests from. It must have no significant bits outside of the
```suggestion
        - `client`: The client’s address or a subnet of the client’s address from which the set of upstream servers should resolve requests. It must have no significant bits outside the subnet mask.
```

2024-06-14 10:22 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +The `fallback` object configures the behavior of DNS server on failures. It has the following properties:
```suggestion
The `fallback` object configures the behavior of the DNS server in case of failure. It has the following properties:
```

2024-06-14 10:23 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +    **Example:** `syslog`
а тут ок с отступом?

2024-06-14 10:23 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +- `format`: Specifies format of the log entries.
```suggestion
- `format`: Specifies the format of the log entries.
```

2024-06-14 10:24 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +    - `adguard_legacy`;
мы вроде пишем без знаков препинания в таких случаях. будем убирать или не надо?

2024-06-14 10:24 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +- `timestamp`: Specifies if the log entries should contain timestamp.
```suggestion
- `timestamp`: Specifies whether to include a timestamp in the log entries.
```

2024-06-14 10:25 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +- `verbose`: Specifies if the log should be more informative.
```suggestion
- `verbose`: Specifies whether the log should be more informative.
```

2024-06-14 10:26 UTC, ss-orlova commented on docs/dns-client/environment.md
> +AdGuard DNS Client uses [environment variables][wiki-env] to store some of the configuration. All other configuration is stored in the [configuration file][conf].
просто предложение
```suggestion
AdGuard DNS Client uses [environment variables][wiki-env] to store part of the configuration. The rest of the configuration is stored in the [configuration file][conf].
```

2024-06-14 10:29 UTC, ss-orlova commented on docs/dns-client/environment.md
> +- `adguard_legacy`;
тут бы тоже убрала знаки препинания

2024-06-14 10:31 UTC, ss-orlova commented on docs/dns-client/environment.md
> +This environment variable has priority over [log.timestamp][conf-log] field from the configuration file.
```suggestion
This environment variable has priority over the [log.timestamp][conf-log] field in the configuration file.
```

2024-06-14 10:31 UTC, ss-orlova commented on docs/dns-client/environment.md
> +This environment variable has priority over [log.verbose][conf-log] field from the configuration file.
```suggestion
This environment variable has priority over the [log.verbose][conf-log] field in the configuration file.
```

2024-06-14 10:33 UTC, ss-orlova commented on docs/dns-client/overview.md
> +:::note
предложила бы больше насторожить

```suggestion
:::caution
```

2024-06-14 10:33 UTC, ss-orlova commented on docs/dns-client/overview.md
> +AdGuard DNS Client is still in the Beta stage. Things will break and there are still bugs.
```suggestion
AdGuard DNS Client is still in the beta stage. It may be unstable.
```

2024-06-14 10:35 UTC, ss-orlova commented on docs/dns-client/overview.md
> +Any option overrides the corresponding value provided by configuration file.
```suggestion
Each option overrides the corresponding value provided by the configuration file.
```

2024-06-14 10:36 UTC, ss-orlova commented on docs/dns-client/overview.md
> +- `0`: AdGuardDNSClient successfully finished and exited, no errors.
а название специально слитно написано?

2024-06-14 14:50 UTC, ainar-g commented on docs/dns-client/environment.md
> +- `adguard_legacy`;
Это же список.  А вот пояснение к нему напишу.

2024-06-14 14:52 UTC, ainar-g commented on docs/dns-client/configuration.md
> +    - `adguard_legacy`;
Не пишем знаков в списках?

2024-06-14 14:52 UTC, ainar-g commented on docs/dns-client/configuration.md
> +    **Example:** `syslog`
Да, так как это пример для всего поля, а те, что выше, для одного из типов.

2024-06-14 14:54 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +    - `adguard_legacy`;
ага

2024-06-14 15:02 UTC, ainar-g commented on docs/dns-client/configuration.md
> +The `dns` object configures the behavior of DNS server. It has the following properties:
Не до конца понял, о чём ты?

2024-06-14 15:06 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +The `dns` object configures the behavior of DNS server. It has the following properties:
после этой фразы ждешь списка, а по факту просто новые подзаголовки, просто следующего уровня. кажется, что что-то пропущено

2024-06-14 15:07 UTC, ss-orlova commented on docs/dns-client/configuration.md
> +The `dns` object configures the behavior of DNS server. It has the following properties:
может вытащить эти названия, оформить списком, а дальше уже расписать подробнее с подзаголовками?

2024-06-14 15:09 UTC, ainar-g commented on docs/dns-client/configuration.md
> +The `dns` object configures the behavior of DNS server. It has the following properties:
Я бы так и делал, но у вас нельзя давать ссылки на элементы списка.  А ссылки на эти свойства понадобятся.

2024-06-14 15:19 UTC, ss-orlova approved these changes

2024-06-17 14:24 UTC, vbagirov requested changes

2024-06-17 14:24 UTC, vbagirov commented on docs/dns-client/configuration.md
> +        :::note
проверить не могу, а точно при смещении :::note относительно начала строки ничего не поедет нигде?

2024-06-17 14:24 UTC, vbagirov commented on docs/dns-client/overview.md
> +A cross-platform lightweight DNS client for [AdGuard DNS]. It operates as a DNS server that forwards DNS requests to the corresponding upstream resolvers.
есть опасение, что так не будет работать и надо либо `[AdGuard DNS][AdGuard DNS]`, либо `[AdGuard DNS][]`

2024-06-17 14:24 UTC, vbagirov commented on docs/dns-client/overview.md
> +The YAML configuration file is described in the [`configuration.md`] file, and there is also a sample configuration file `config.dist.yaml`.  Some configuration parameters can also be overridden usin
Здесь комментарий аналогичный предыдущему

2024-06-17 14:24 UTC, vbagirov commented on docs/dns-client/overview.md
> +- `0`: Successfully finished and exited, no errors.
корректно ли называть это error code?

2024-06-17 14:32 UTC, ainar-g commented on docs/adguard-home/faq.md
> +This error message means that AdGuard Home was unable to reach AdGuard servers to check for updates and/or download them. This could mean that the servers are blocked by your ISP or are temporarily d
Это имя бинаря, так что добавлю моноспейс.

2024-06-17 14:33 UTC, ainar-g commented on docs/dns-client/overview.md
> +- `0`: Successfully finished and exited, no errors.
Это exit codes, конечно.  Поправлю.

2024-06-17 14:42 UTC, vbagirov approved these changes

2024-06-17 14:56 UTC, merged