Add "JSON API for DNS" section to AdGuard DNS protocol description
AdguardTeam/KnowledgeBaseDNS pull request #233
Opened 2024-08-16 18:01 UTC by vbagirov

2024-08-17 18:16 UTC, el-termikael requested changes

2024-08-17 18:16 UTC, el-termikael commented on docs/public-dns/overview.md
> +AdGuard DNS also provides a JSON API for DNS. It is possible to get a DNS response in JSON by typing in:
by entering or just by typing without in would be better, I guess

2024-08-17 18:16 UTC, el-termikael commented on docs/public-dns/overview.md
> +Unlike with Google DNS, AdGuard DNS doesn't support `edns_client_subnet` and `Comment` values in response JSONs.
`comment` with a small с?

2024-08-19 09:23 UTC, ameshkov approved these changes

2024-08-19 09:27 UTC, vbagirov commented on docs/public-dns/overview.md
> +Unlike with Google DNS, AdGuard DNS doesn't support `edns_client_subnet` and `Comment` values in response JSONs.
Documentation has it with capital C

2024-08-19 10:44 UTC, ameshkov approved these changes

2024-08-19 10:56 UTC, el-termikael approved these changes

2024-08-19 10:57 UTC, merged