Update dns-providers.md
AdguardTeam/KnowledgeBaseDNS pull request #236
Opened 2024-08-20 01:37 UTC by BastCo

Updated JupitrDNS description and IP

2024-08-20 13:12 UTC, el-termikael requested changes

2024-08-20 13:12 UTC, el-termikael commented on docs/general/dns-providers.md
> +[JupitrDNS](https://jupitrdns.com/) is a free security focused recursive DNS service that blocks malware. It has DNSSEC support and does not store logs.
```suggestion
[JupitrDNS](https://jupitrdns.com/) is a free security-focused recursive DNS service that blocks malware. It has DNSSEC support and does not store logs.

2024-08-20 13:29 UTC, BastCo reviewed
Fixed

2024-08-20 16:07 UTC, BastCo reviewed
Fixed Add to AdGuard VPN

2024-08-21 09:43 UTC, el-termikael approved these changes

2024-09-10 07:53 UTC, el-termikael approved these changes

2024-09-10 07:53 UTC, merged