[AGM-2231] Add an article about Rate limit to KB
AdguardTeam/KnowledgeBaseDNS pull request #259
Opened 2024-10-24 09:58 UTC by DashaBu

added an article about ‘rate limit’ to the private DNS and included a part about it in the public DNS overview

2024-10-24 10:14 UTC, vbagirov requested changes

2024-10-24 10:14 UTC, vbagirov commented on docs/private-dns/server-and-settings/rate-limit.md
> + [Rate limit](https://cdn.adtidy.org/content/kb/dns/private/rate_limit.png)
Это сейчас как ссылка добавлено, а не как изображение

2024-10-28 10:01 UTC, vbagirov requested changes

2024-10-28 10:01 UTC, vbagirov commented on docs/private-dns/server-and-settings/rate-limit.md
> + ![Rate limit](https://cdn.adtidy.org/content/kb/dns/private/rate_limit.png)
Возможно, стоит попробовать сделать отступы до и после скриншота. Кажется, что сейчас слишком липнет на соседние строки

2024-10-28 10:19 UTC, vbagirov approved these changes

2024-10-28 12:18 UTC, ameshkov reviewed
One minor comment. If resolved, this can be merged

2024-10-28 12:47 UTC, merged