Update dns-providers.md
AdguardTeam/KnowledgeBaseDNS pull request #273
Opened 2024-12-07 20:52 UTC by futureshield

added FutureDNS as a provider

2024-12-11 12:31 UTC, el-termikael requested changes

2024-12-11 12:31 UTC, el-termikael commented on docs/general/dns-providers.md
> +[FutureDNS](https://futuredns.eu.org) is a privacy-focused DNS service that prioritizes user security and anonymity. We support both standard DNS and encrypted protocols while maintaining a strict no
```suggestion
[FutureDNS](https://futuredns.eu.org) is a privacy-focused DNS service that prioritizes user security and anonymity. It supports both standard DNS and encrypted protocols while maintaining a strict no-logging policy.
```

2024-12-11 12:31 UTC, el-termikael commented on docs/general/dns-providers.md
> +
please leave only one blank line

2024-12-12 21:57 UTC, futureshield commented
i think it's fixed now sorry

2024-12-13 08:27 UTC, el-termikael approved these changes

2024-12-13 08:41 UTC, merged

2024-12-13 08:41 UTC, el-termikael commented
@futureshield thank you for your contribution! now it's merged