AGDNS-585 start
AdguardTeam/KnowledgeBaseDNS pull request #3
Opened 2022-03-11 15:39 UTC by vyanovsky

private dns

2022-03-15 07:48 UTC, vbagirov requested changes

2022-03-15 07:48 UTC, vbagirov commented on docs/private-dns/overview.md
> +<p><img src="https://cdn.adguard.com/public/Adguard/Blog/private_adguard_dns/main.png" style="max-height: 600px; padding: 2px;">
В докузавре не используем хтмл вообще. Ну уж точно не для картинок. Так что должно быть так:

`![описание](https://cdn.adguard.com/public/Adguard/Blog/private_adguard_dns/main.png)`

Ну и везде, где картинки, аналогично

2022-03-15 07:48 UTC, vbagirov commented on docs/private-dns/overview.md
>  ---
У тебя в шапке должен быть title типа "Private AdGuard DNS" или вроде того, а то что такое просто Overview - непонятно. Ну и sidebar position поставь наверное 5.

2022-03-15 07:48 UTC, vbagirov commented on docs/private-dns/overview.md
>  # Private AdGuard DNS
Первый уровень заголовков не нужен, это по сути тайтл

2022-03-15 07:48 UTC, vbagirov commented on docs/private-dns/overview.md
> +### What is Private AdGuard DNS
А здесь и везде поменяй `###` на `##`

2022-03-15 07:48 UTC, vbagirov commented on docs/private-dns/overview.md
> +Earlier, we were able to offer either a public AdGuard DNS server or AdGuard Home for "cleaning up the Internet". These solutions worked for some users, but for many of them, the public AdGuard DNS l
Это звучит как статья из блога, где мы говорим о событии запуска Public AdGuard DNS, а здесь скорее нужно matter-of-facty рассказывать о том, как есть. Т.е. описательный текст вместо повествовательного.

2022-03-15 07:48 UTC, vbagirov commented on docs/private-dns/overview.md
> +Earlier, we were able to offer either a public AdGuard DNS server or AdGuard Home for "cleaning up the Internet". These solutions worked for some users, but for many of them, the public AdGuard DNS l
И надо бы добавить ссылок: там где Public AdGuard DNS - на соотв. статью в этой кб (почитай документацию Docusaurus или спроси у меня как), а там где AG Home - пока что на гитхаб хомяка.

2022-03-15 07:48 UTC, vbagirov commented on docs/private-dns/overview.md
> +With the private DNS server, you'll be able to set which domains you want to block and which you don't. This will work the same way as the public AdGuard DNS, but with one change: now it's your decis
тут надо явно написать что можно добавлять собственные блоклисты, а не только использовать те, что доступны по дефолту.

2022-03-15 07:48 UTC, vbagirov commented on docs/private-dns/overview.md
> +For those who aren't satisfied with dozens of pre-installed *Blocklists* with thousands of rules, we've provided a handy function to import custom rules. If you have a list of [DNS filtering rules](h
upload to the service как-то странно звучит на мой взгляд.

Плюс можно не только импортировать, но и просто руками добавлять

2022-03-15 07:48 UTC, vbagirov commented on docs/private-dns/overview.md
> +For those who aren't satisfied with dozens of pre-installed *Blocklists* with thousands of rules, we've provided a handy function to import custom rules. If you have a list of [DNS filtering rules](h
Ссылка тоже будет другая на филтеринг синтакс, надо сделать аналогично тому как выше я писал, на соседнюю статью. В документации это есть

2022-03-15 07:48 UTC, vbagirov commented on docs/private-dns/overview.md
> +
Тут не хватает где-то ещё пунктов про фичи Traffic destination, Top companies и про Query Log.

2022-03-15 16:36 UTC, vyanovsky commented on docs/private-dns/overview.md
>  Here is a simple sum up of differences in available features between Public AdGuard DNS and Private AdGuard DNS servers.
мб вообще лучше
Here is a simple comparison of features available

2022-03-15 16:38 UTC, vyanovsky commented on docs/private-dns/overview.md
> +This is a detailed log where you can check out the information on every single request and also sort requests by status, type, company, device, time, country.
нельзя

2022-03-15 16:52 UTC, vyanovsky commented on docs/private-dns/overview.md
> +![](https://cdn.adguard.com/public/Adguard/Blog/private_adguard_dns/main.png)
☑️

2022-03-15 16:52 UTC, vyanovsky commented on docs/private-dns/overview.md
> +This feature shows you where do DNS requests from your devices go. On top of seeing the map of request destinations, you can filter the information by date, device and country.
☑️

2022-03-15 16:59 UTC, vbagirov commented on docs/private-dns/overview.md
>  Here is a simple sum up of differences in available features between Public AdGuard DNS and Private AdGuard DNS servers.
существительное sum-up, если верить гуглу, так что в любом случае надо поправить. Можно на ту версию что ты предлагаешь

2022-03-16 08:44 UTC, vbagirov approved these changes

2022-03-16 09:16 UTC, merged