AGDNS-586
AdguardTeam/KnowledgeBaseDNS pull request #5
Opened 2022-03-14 09:16 UTC by NataKiss

только скопировала

2022-03-15 09:17 UTC, vbagirov requested changes

2022-03-15 09:17 UTC, vbagirov commented on docs/public-dns/overview.md
> +AdGuard DNS is a free, privacy-oriented DNS resolution system that blocks tracking, ads and phishing. AdGuard DNS does not require installing any applications. It is easy to use, can be effortlessly
наверное не очень правильно писать minimal

2022-03-15 09:17 UTC, vbagirov commented on docs/public-dns/overview.md
> +AdGuard DNS is a free, privacy-oriented DNS resolution system that blocks tracking, ads and phishing. AdGuard DNS does not require installing any applications. It is easy to use, can be effortlessly
Ещё в этом абзаце надо как то подчеркнуть, что блочить рекламу это опция, но можно пользоваться AdGuard DNS и без этого

2022-03-15 09:17 UTC, vbagirov commented on docs/public-dns/overview.md
> +## Public AdGuard DNS servers
Надо более явно где-то тут прописать типа "Вот ссылка с подробными инструкциями по настройки паблик днс серверов"

2022-03-15 09:17 UTC, vbagirov commented on docs/public-dns/overview.md
> +AdGuard DNS is a free, privacy-oriented DNS resolution system that blocks tracking, ads and phishing. AdGuard DNS does not require installing any applications. It is easy to use, can be effortlessly
Ещё наверное коротко напиши, где можно использовать паблик днс серверы: на любых мобильных и десктопных устройствах, роутерах, игровых консолях и т.д.

2022-03-15 09:17 UTC, vbagirov commented on docs/public-dns/overview.md
> +DoH) and DoT are modern secure DNS protocols that gain more and more popularity and will become the industry standards for the foreseeable future. Both are more reliable than DNSCrypt and both are su
Здесь что-то со скобкой

2022-03-15 09:17 UTC, vbagirov commented on docs/public-dns/overview.md
> +### DNSCrypt protocol
можно тут и далее убрать protocol из заголовка

2022-03-15 09:17 UTC, vbagirov commented on docs/public-dns/overview.md
> +AdGuard DNS allows you to use a specific encrypted protocol — DNSCrypt. Thanks to it, all DNS requests are being encrypted, which protects you from possible request interception and subsequent eavesd
Здесь добавь что DNSCrypt считается сравнительно устаревшим протоколом в сравнении с DoH, DoT и DoQ и что мы советуем использовать другие протоколы, если есть такая возможность

2022-03-15 09:17 UTC, vbagirov commented on docs/public-dns/overview.md
> +DNS-over-QUIC is a new DNS encryption protocol and AdGuard DNS is the first public resolver that supports it. Unlike DoH and DoT, it uses QUIC as a transport protocol and finally brings DNS back to i
сюда ссылку на статью в нашем блоге про DoQ

2022-03-15 11:15 UTC, NataKiss commented on docs/public-dns/overview.md
> +DoH) and DoT are modern secure DNS protocols that gain more and more popularity and will become the industry standards for the foreseeable future. Both are more reliable than DNSCrypt and both are su
вроде исправила, хз что с ней

2022-03-15 15:36 UTC, vbagirov requested changes

2022-03-15 15:36 UTC, vbagirov commented on docs/public-dns/overview.md
> +AdGuard DNS is a free, privacy-oriented DNS resolution system that provides secure connection and also can block tracking, ads, phishing and adult content (optionally). AdGuard DNS does not require i
>privacy-oriented DNS resolution system

privacy-oriented DNS resolver - так лучше

2022-03-15 15:36 UTC, vbagirov commented on docs/public-dns/overview.md
> +## Public AdGuard DNS servers
коммент был про то что явно надо в этом разделе ссылку на настройку дать. Здесь же речь про серверы. А во вступитеьном как раз это не так важно

2022-03-15 15:36 UTC, vbagirov commented on docs/public-dns/overview.md
> +AdGuard DNS allows you to use a specific encrypted protocol — DNSCrypt. Thanks to it, all DNS requests are being encrypted, which protects you from possible request interception and subsequent eavesd
я бы не сказал что DoH и DoT прям brand new. Просто они во всём практически превосходят устаревший DNSCrypt

2022-03-15 15:36 UTC, vbagirov commented on docs/public-dns/overview.md
>  AdGuard DNS supports various protocols, so you can choose the one that suits you best.
Кстати подумал что наверное надо добавить про Plain DNS раздел, написать что конечно же мы поддерживаем плейн, как IPv4 так и IPv6, но рекомендуем всё же использовать зашифрованные

2022-03-15 16:39 UTC, NataKiss commented on docs/public-dns/overview.md
>  AdGuard DNS supports various protocols, so you can choose the one that suits you best.
Андрей говорил, что и так уже много инфы

2022-03-16 08:42 UTC, vbagirov requested changes

2022-03-16 08:42 UTC, vbagirov commented on docs/public-dns/overview.md
> +Each server supports different secure protocols: DNSCrypt, DNS-over-HTTPS (DoH), DNS-over-TLS (DoT), and DNS-over-QUIC (DoQ). You can find detailed instructions on setting up AdGuard DNS on any devic
Давай эту фразу про детальные инструкции запихнем в конец предыдущего абзаца, после "doesn't block anything"

2022-03-16 08:42 UTC, vbagirov commented on docs/public-dns/overview.md
>  AdGuard DNS supports various protocols, so you can choose the one that suits you best.
Тем не менее, нельзя не сказать что мы поддерживаем плейн. Давай тупо так  сделаем, поменяем это предложение:

Besides plain DNS (both IPv4 and IPv6) AdGuard DNS supports various encrypted protocols, so you can choose the one that suits you best.

2022-03-16 09:17 UTC, vbagirov approved these changes

2022-03-16 09:17 UTC, merged