update ibksturm
AdguardTeam/KnowledgeBaseDNS pull request #68
Opened 2022-09-14 20:17 UTC by ibksturm

2022-11-18 11:36 UTC, el-termikael requested changes

2022-11-18 11:36 UTC, el-termikael commented on docs/general/dns-providers.md
> + |
an extra pipe

2023-02-28 09:32 UTC, el-termikael commented
Hi @ibksturm 
Could you please remove an extra pipe?

2023-04-21 13:49 UTC, ibksturm commented
> Hi @ibksturm Could you please remove an extra pipe?

Hi There :)

What do you mean with that? Sorry i don't understand :(

2023-04-24 11:24 UTC, el-termikael approved these changes

2023-04-25 09:07 UTC, merged